### PR TITLE
Fix issue#142

### LINKED ISSUE #142: Associate "Measurement" model to multiple other models
We'd like to measure information about multiple entities in the lab at once. To this end, we'd like to associate the following models to `Measurement`s: `Tank, Animal, Family`. In order to do this we will need to:

- [ ] Sever `has_many through...` association from Tanks -> MeasurementEvent -> Measurement
- [ ] Add the new associations

**Example Use Case**
When we measure the count of a family in a tank, we'd like to directly associate that information with the Family and the Tank.

**Acceptance Criterion**
- [ ] Tank, Animal, Family all `have_many` measurements.
- [ ] Measurements belong_to Tank, Animal, Family
- [ ] The belong_to is optional:true
- [ ] Add appropriate specs
- [ ] Green build (can "Xit" uploader specs if necessary - but explicitly mention it in your PR if you do)

Note: The csv modifications are out of scope and will be addressed in #237

### PR DESCRIPTION
**Pull request by Miguel-Enrique13**
CHANGED models Tank, Family, Animal to reference Measurement.
CHANGED model Measurement to reference Tank, Family, Animal.
CREATED migrations.
CHANGED Tank, Family, Measurement, Animal specs for added references.

Co-authored-by: David Carmo <Dmcarmo@gmail.com>
Co-authored-by: Miguel Guardia <guardia@ualberta.ca>

Resolves #142 

### Type of change

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not 
work as expected)
* This change requires a documentation update
* Documentation update

### CODE REVIEW

File: app/models/measurement.rb [hunk 1]
```diff
@@ -10,20 +13,20 @@ class Measurement < ApplicationRecord
     VALUE: "value"
   }.freeze
 
-  delegate :tank, to: :measurement_event
+  # delegate :tank, to: :measurement_event
```
Comment (mdworken) [inline app/models/measurement.rb:16]: Let's delete this in the future - I don't think it'll ever come back.

**Review by mdworken — APPROVED** [review]
Excellent work, thanks so much for the contribution!
